# Generated by Django 4.2.19 on 2025-02-10 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Машина', 'verbose_name_plural': 'Машины'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='complaint',
            options={'verbose_name': 'Рекламация', 'verbose_name_plural': 'Рекламации'},
        ),
        migrations.AlterModelOptions(
            name='failurenode',
            options={'verbose_name': 'Узел отказа', 'verbose_name_plural': 'Узлы отказа'},
        ),
        migrations.AlterModelOptions(
            name='modelreference',
            options={'verbose_name': 'Модель техники', 'verbose_name_plural': 'Модели техник'},
        ),
        migrations.AlterModelOptions(
            name='recoverymethod',
            options={'verbose_name': 'Способ восстановления', 'verbose_name_plural': 'Способы восстановления'},
        ),
        migrations.AlterModelOptions(
            name='servicecompany',
            options={'verbose_name': 'Сервисная компания', 'verbose_name_plural': 'Сервисные компании'},
        ),
        migrations.AlterModelOptions(
            name='technicalmaintenance',
            options={'verbose_name': 'ТО', 'verbose_name_plural': 'ТО'},
        ),
        migrations.AlterField(
            model_name='car',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='app.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='car',
            name='controlled_bridge_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='controlled_bridges', to='app.modelreference', verbose_name='Модель управляемого моста'),
        ),
        migrations.AlterField(
            model_name='car',
            name='date_of_shipment_from_the_factory',
            field=models.DateField(verbose_name='Дата отгрузки с завода'),
        ),
        migrations.AlterField(
            model_name='car',
            name='delivery_address',
            field=models.TextField(verbose_name='Адрес поставки (эксплуатации)'),
        ),
        migrations.AlterField(
            model_name='car',
            name='delivery_contract_number_and_date',
            field=models.TextField(verbose_name='Договор поставки №, дата'),
        ),
        migrations.AlterField(
            model_name='car',
            name='driving_bridge_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='driving_bridges', to='app.modelreference', verbose_name='Модель ведущего моста'),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='engines', to='app.modelreference', verbose_name='Модель двигателя'),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_serial_number',
            field=models.CharField(max_length=255, unique=True, verbose_name='Заводской № двигателя'),
        ),
        migrations.AlterField(
            model_name='car',
            name='equipment',
            field=models.TextField(verbose_name='Комплектация (доп. опции)'),
        ),
        migrations.AlterField(
            model_name='car',
            name='factory_number_of_controlled_bridge',
            field=models.CharField(max_length=255, unique=True, verbose_name='Зав. № управляемого моста'),
        ),
        migrations.AlterField(
            model_name='car',
            name='factory_number_of_drive_axle',
            field=models.CharField(max_length=255, unique=True, verbose_name='Зав. № ведущего моста'),
        ),
        migrations.AlterField(
            model_name='car',
            name='factory_number_of_transmission',
            field=models.CharField(max_length=255, unique=True, verbose_name='Заводской № трансмиссии'),
        ),
        migrations.AlterField(
            model_name='car',
            name='machines_factory_number',
            field=models.CharField(max_length=255, unique=True, verbose_name='Заводской № машины'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model_of_technique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='app.modelreference', verbose_name='Модель техники'),
        ),
        migrations.AlterField(
            model_name='car',
            name='recipient',
            field=models.TextField(verbose_name='Грузополучатель (конечный потребитель)'),
        ),
        migrations.AlterField(
            model_name='car',
            name='service_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='app.servicecompany', verbose_name='Сервисная компания'),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transmissions', to='app.modelreference', verbose_name='Модель трансмиссии'),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact_info',
            field=models.TextField(blank=True, null=True, verbose_name='Контактные данные клиента'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Имя клиента'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complaint_car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='app.car', verbose_name='Машина'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complaint_operating_time',
            field=models.FloatField(verbose_name='Наработка, м/час'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='date_of_refusal',
            field=models.DateField(verbose_name='Дата отказа'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='date_of_restoration',
            field=models.DateField(verbose_name='Дата восстановления'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='description_of_failure',
            field=models.TextField(verbose_name='Описание отказа'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='equipment_downtime',
            field=models.FloatField(editable=False, verbose_name='Время простоя техники'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='failure_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to='app.failurenode', verbose_name='Узел отказа'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='recovery_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to='app.recoverymethod', verbose_name='Способ восстановления'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='service_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to='app.servicecompany', verbose_name='Cервисная компания'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='used_spare_parts',
            field=models.TextField(verbose_name='Используемые запасные части'),
        ),
        migrations.AlterField(
            model_name='failurenode',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание узла отказа'),
        ),
        migrations.AlterField(
            model_name='failurenode',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название узла отказа'),
        ),
        migrations.AlterField(
            model_name='modelreference',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание модели'),
        ),
        migrations.AlterField(
            model_name='modelreference',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название модели'),
        ),
        migrations.AlterField(
            model_name='recoverymethod',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание способа'),
        ),
        migrations.AlterField(
            model_name='recoverymethod',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название способа'),
        ),
        migrations.AlterField(
            model_name='servicecompany',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание компании'),
        ),
        migrations.AlterField(
            model_name='servicecompany',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='technicalmaintenance',
            name='date_of_maintenance',
            field=models.DateField(verbose_name='Дата проведения ТО'),
        ),
        migrations.AlterField(
            model_name='technicalmaintenance',
            name='order_date',
            field=models.DateField(verbose_name='Дата заказ-наряда'),
        ),
        migrations.AlterField(
            model_name='technicalmaintenance',
            name='order_number',
            field=models.TextField(verbose_name='№ заказ-наряда'),
        ),
        migrations.AlterField(
            model_name='technicalmaintenance',
            name='organization_carried_out_maintenance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_organizations', to='app.servicecompany', verbose_name='Организация, проводившая ТО'),
        ),
        migrations.AlterField(
            model_name='technicalmaintenance',
            name='service_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='technical_maintenances', to='app.servicecompany', verbose_name='Сервисная компания'),
        ),
        migrations.AlterField(
            model_name='technicalmaintenance',
            name='to_car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_maintenances', to='app.car', verbose_name='Машина'),
        ),
        migrations.AlterField(
            model_name='technicalmaintenance',
            name='to_operating_time',
            field=models.FloatField(verbose_name='Наработка, м/час'),
        ),
        migrations.AlterField(
            model_name='technicalmaintenance',
            name='type_of_maintenance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_types', to='app.servicecompany', verbose_name='Вид ТО'),
        ),
    ]
