# Generated by Django 4.2.19 on 2025-02-10 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_car_options_alter_client_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelreference',
            name='name',
        ),
        migrations.AddField(
            model_name='modelreference',
            name='driving_bridge_model',
            field=models.CharField(default=1, max_length=255, unique=True, verbose_name='Название модели ведущего моста'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelreference',
            name='model_of_engine',
            field=models.CharField(default=1, max_length=255, unique=True, verbose_name='Название модели двигателя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelreference',
            name='model_of_technique',
            field=models.CharField(default=1, max_length=255, unique=True, verbose_name='Название модели техники'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelreference',
            name='model_of_transmission',
            field=models.CharField(default=1, max_length=255, unique=True, verbose_name='Название модели трансмиссии'),
            preserve_default=False,
        ),
    ]
