# Generated by Django 4.2.19 on 2025-02-10 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_modelreference_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelreference',
            name='model_of_technique',
        ),
        migrations.AddField(
            model_name='modelreference',
            name='name',
            field=models.CharField(default=1, max_length=255, unique=True, verbose_name='Название модели'),
            preserve_default=False,
        ),
    ]
