# Generated by Django 4.2.19 on 2025-02-11 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_car_driving_bridge_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelControlledBridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Модель управляемого моста')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание управляемого моста')),
            ],
            options={
                'verbose_name': 'Модель управляемого моста',
                'verbose_name_plural': 'Модели управляемых мостов',
            },
        ),
        migrations.CreateModel(
            name='ModelDrivingBridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Модель ведущего моста')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание ведущего моста')),
            ],
            options={
                'verbose_name': 'Модель ведущего моста',
                'verbose_name_plural': 'Модели ведущих мостов',
            },
        ),
        migrations.CreateModel(
            name='ModelEngine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Модель двигателя')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание двигателя')),
            ],
            options={
                'verbose_name': 'Модель двигателя',
                'verbose_name_plural': 'Модели двигателей',
            },
        ),
        migrations.CreateModel(
            name='ModelTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Модель техники')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание техники')),
            ],
            options={
                'verbose_name': 'Модель техники',
                'verbose_name_plural': 'Модели техник',
            },
        ),
        migrations.CreateModel(
            name='ModelTransmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Модель трансмиссии')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание трансмиссии')),
            ],
            options={
                'verbose_name': 'Модель трансмиссии',
                'verbose_name_plural': 'Модели трансмиссий',
            },
        ),
        migrations.CreateModel(
            name='TypeMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Вид ТО')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание ТО')),
            ],
            options={
                'verbose_name': 'Вид ТО',
                'verbose_name_plural': 'Виды ТО',
            },
        ),
        migrations.AlterField(
            model_name='car',
            name='delivery_address',
            field=models.CharField(max_length=255, verbose_name='Адрес поставки (эксплуатации)'),
        ),
        migrations.AlterField(
            model_name='car',
            name='delivery_contract_number_and_date',
            field=models.CharField(max_length=255, verbose_name='Договор поставки №, дата'),
        ),
        migrations.AlterField(
            model_name='car',
            name='recipient',
            field=models.CharField(max_length=255, verbose_name='Грузополучатель (конечный потребитель)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя клиента'),
        ),
        migrations.AlterField(
            model_name='servicecompany',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание сервис.компании'),
        ),
        migrations.AlterField(
            model_name='servicecompany',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название сервис.компании'),
        ),
        migrations.AlterField(
            model_name='technicalmaintenance',
            name='order_number',
            field=models.CharField(max_length=255, verbose_name='№ заказ-наряда'),
        ),
        migrations.AlterField(
            model_name='car',
            name='controlled_bridge_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='controlled_bridges', to='app.modelcontrolledbridge', verbose_name='Модель управляемого моста'),
        ),
        migrations.AlterField(
            model_name='car',
            name='driving_bridge_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='driving_bridges', to='app.modeldrivingbridge', verbose_name='Модель ведущего моста'),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='engines', to='app.modelengine', verbose_name='Модель двигателя'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model_of_technique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='app.modeltechnique', verbose_name='Модель техники'),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transmissions', to='app.modeltransmission', verbose_name='Модель трансмиссии'),
        ),
        migrations.AlterField(
            model_name='technicalmaintenance',
            name='type_of_maintenance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_types', to='app.typemaintenance', verbose_name='Вид ТО'),
        ),
        migrations.DeleteModel(
            name='ModelReference',
        ),
    ]
