# Generated by Django 4.2.19 on 2025-02-27 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
