# Generated by Django 4.2.19 on 2025-03-12 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='app.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='car',
            name='controlled_bridge_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='controlled_bridges', to='app.modelcontrolledbridge', verbose_name='Модель управляемого моста'),
        ),
        migrations.AlterField(
            model_name='car',
            name='driving_bridge_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='driving_bridges', to='app.modeldrivingbridge', verbose_name='Модель ведущего моста'),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='engines', to='app.modelengine', verbose_name='Модель двигателя'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model_of_technique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='app.modeltechnique', verbose_name='Модель техники'),
        ),
        migrations.AlterField(
            model_name='car',
            name='service_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='app.servicecompany', verbose_name='Сервисная компания'),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transmissions', to='app.modeltransmission', verbose_name='Модель трансмиссии'),
        ),
    ]
