# Generated by Django 4.2.19 on 2025-03-16 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0015_alter_car_client_alter_car_controlled_bridge_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Имя модели грузополучателя')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Модель грузополучателя',
                'verbose_name_plural': 'Модели грузополучателя',
            },
        ),
        migrations.AlterField(
            model_name='car',
            name='recipient',
            field=models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='app.recipient', verbose_name='Грузополучатель (конечный потребитель)'),
        ),
    ]
